### ISSUE TITLE
Define interface and scheme for the Merkle tree

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#10]

**Comment by TomTaehoonKim** [comment]
**Merkle Tree**
Time complexity: Searching, Insertion, Deletion - O(log n)
Space complexity: O(n)
where n is the number of nodes consisting the tree.

**Merkle Patricia Trie**
Time complexity: Searching, Insertion, Deletion - O(m),
Space complexity: O(nm)
where m is the length of a string and n is the number of strings stored in the merkle patricia trie.

**Comment by TomTaehoonKim** [comment]
Ethereum stores its current state with [modified merkle patricia trie](https://ethereum.org/en/developers/docs/data-structures-and-encoding/patricia-merkle-trie/).

In MPT, state root's hash can be quickly calculated by only recalculating the hashes of the modified branches; instead of looking at the whole state trie to calculate the root hash.

MPT minimizes the number of newly added nodes. For example, in this [figure](https://i.stack.imgur.com/DZ5r1.png) the only difference between block 180993 and block 180994 is the balance of Account 100 from 30 to 50. In this case, most of the other nodes can be reused except some parent nodes of the updated node. So, only 4 nodes are added in this case.

**Comment by TomTaehoonKim** [comment]
Since state changes frequently, data structure that allows quick recalculation of the root hash after insert, edit, delete operation would be a huge advantage.

**Comment by TomTaehoonKim** [comment]
MPT's advantage in terms of states is evident; however, I've concluded that MPT's advantage is not that big considering the structural complexity of MPT.

**Comment by TomTaehoonKim** [comment]
# Update
Currently [implementing OneshotMerkleTree](https://github.com/postech-dao/simperby/pull/43) for transaction trees.

## TODO
For state tries, it has been concluded that a different implementation is necessary after discussion with @junha1.
However, state tries are not necessary for our MVP, so we are going to implement just transaction trees for now.
