### ISSUE TITLE
Improve delegation protocol

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#49]
mitigation of the prevention of multi-level delegation would be helpful

**Comment by lemonholic** [comment]
If we forbid chained delegations, we have to get permission from both delegator and delegatee. Otherwise, delegation to a random node will prevent the node from delegating to another, regardless of its will. Currently, it seems that only delegator's permission is required to make a delegation.

Refer to: https://github.com/postech-dao/simperby/pull/48#discussion_r950844812

**Comment by lemonholic** [comment]
We may have a state transition rule that lets a node to make itself "delegatable", which means the node has permitted other nodes to delegate the voting power to it.
