### ISSUE TITLE
Make the initial broadcaster not responsible for the task

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#71]
Broadcasted packet must be re-broadcasted even if the original broadcaster goes offline.

**Comment by lemonholic** [comment]
That property was not considered while I've been implementing network module.
I'll think of it through the next few days.

**Comment by lemonholic** [comment]
libp2p has GossipSub module which implements Pub/Sub model on a gossip network.
[An easy-to-understand desc. of GossipSub](https://docs.libp2p.io/concepts/publish-subscribe/).

Peers on the network gossip about "recently seen messages". Those who haven't seen a specific message send a request to pull the message. We might resolve this issue if the parameters for the message cache are well tailored.

However, simperby is designed to have a long period between two block creations. Theoretically, there might be a unlimited number of gossip messages broadcast on the network, and it's not good since it will cause heavy traffic. If we want to use GossipSub, an expiration timeout(or block height) should be imposed on every message. (Otherwise we will have to implement our own gossip network)

**Comment by lemonholic** [comment]
If we don't use GossipSub, I'm planning to implement simple gossip network:
- each message is identified by `Hash(random_salt + message)`
- every node should subscribe to the topic for gossiping messages that haven't seen by all nodes to see what's going on
- to pull an unseen message, a node requests to send the message to one of its peer (or it can request to multiple peers to check the integrity of the message)

**Comment by lemonholic** [comment]
Closing it with #83.
