### ISSUE TITLE
Tracking issue for the storage research

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#8]
Our requirements for the storage
1. Key-Value
2. JSON-like schema
3. Simple, Easy, and widely used in other blockchain projects
4. Rust binding

## Tracked issues
- [ ] #10 
- [x] #9

**Comment by Milchstra3e** [comment]
I recommand rocksdb.

### Key-Value

RocksDB is an embeddable persistent key-value store for fast storage.

### JSON-like schema

Sadly, RocksDB doesn't support JSON-like schema.
Therefore, if we want to handle "Value" as JSON object, I would recommand below two options.
+ Naively, use serde_json
+ Define new wrapper for rocksdb

### Simple, Easy, and widely used in other blockchain projects

RocksDB is used by solana, near, polkadot and so on.

### Rust Binding

You can check this below github / documentation

https://github.com/rust-rocksdb/rust-rocksdb
https://docs.rs/rocksdb/latest/rocksdb/

**Comment by Milchstra3e** [comment]
At the beginning, there were several options for db (leveldb, couchdb, rocksdb).

Although leveldb and couchdb can be good solution for another blockchain project, it seems not to be for our project.

Because of lacking functionality and reliability about those db package for rust lang, it is better to choose rocksdb.

Furthermore, rocksdb is used by solana, near, polkadot and so on.

In this reason, I recommand using rocksdb.

**Comment by Milchstra3e** [comment]
## How to Install RocksDB
check this: https://docs.desmos.network/fullnode/rocksdb-installation/

## Basic Operations
+ Get: get value from KVstore with key
+ Put: put value into KVstore with key
+ Delete: delete pair (key, value) from KVstore with key

## User Custom Operations (Merge)
User defined Operation for "Atomic Read-Modify-Write operation" (they said).

**Adventages of it**
+ Encapsulates the semantics for read-modify-write into a simple abstract interface.
+ Allows user to avoid incurring extra cost from repeated Get() calls.
+ Performs back-end optimizations in deciding when/how to combine the operands without changing the underlying semantics.
+ Can, in some cases, amortize the cost over all incremental updates to provide asymptotic increases in efficiency.

More Infomation, check this: https://github.com/facebook/rocksdb/wiki/Merge-Operator

## How to store Key-Value Data

1. **Lazy Evaluation**

    RocksDB takes strategy of lazy evaluation.
    
    In other words, Put or Merge does not necessarily force the value to be computed or the merge to occur immediately.
    
    RocksDB will more-or-less lazily decide when to actually apply the operations
    
    (e.g.: the next time the user calls Get(), or when the system decides to do its clean-up process)

2.  **Log, SST, MANIFEST file**

    log file: candidate key-value to be computed
    
    SST file: actual data storage saving pair (key, value)
    
    MANIFEST file: metadata for current db managing key lists
    
    check this: https://github.com/facebook/rocksdb/wiki/MANIFEST

## Checkpoint

If the snapshot is on the same filesystem as the original database, the SST files will be hard-linked.

otherwise SST files will be copied. The manifest and CURRENT files will be copied.

check this: https://github.com/facebook/rocksdb/wiki/Checkpoints

**Comment by junha1** [comment]
We use git.
